name: api
description: API client package for Hacker News app
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  intl: ^0.19.0

  meta: any
  universal_io: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  freezed: ^2.4.7
  retrofit_generator: ^8.1.0
  flutter_lints: ^3.0.1
  http_mock_adapter: ^0.6.1
  mocktail: ^1.0.3
  

