name: hacker_news

packages:
  - app
  - resources/**

command:
  bootstrap:
    runPubGetInParallel: false
    usePubspecOverrides: true

scripts:
  analyze:
    run: melos exec -c 1 -- fvm flutter analyze .
    description: Run `flutter analyze` in all packages

  format:
    run: melos exec -c 1 -- fvm flutter format .
    description: Run `flutter format` in all packages

  clean:all:
    run: melos exec -c 1 -- fvm flutter clean
    description: Clean all packages

  get:all:
    run: melos exec -c 1 -- fvm flutter pub get
    description: Run pub get in all packages

  build:all:
    run: melos run build:clean && melos run build:gen
    description: Build all generated files for all packages

  build:clean:
    run: melos exec -c 1 -- fvm flutter pub run build_runner clean
    description: Clean all generated files
    
  build:gen:
    run: melos exec -c 1 -- fvm flutter pub run build_runner build --delete-conflicting-outputs
    description: Generate all files for all packages

  cab:
    run: |
      melos clean:all && \
      melos get:all && \
      melos build:all
    description: Clean All Builds (cab) - clean, get dependencies, and generate code

sdkPath: /Users/emirgunumdogdu/Documents/dev/entain_fda/.fvm/versions/3.27.3