name: widgets
description: Widgets package for Hacker News app
version: 0.0.1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  values:
    path: ../values
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  overlay_kit: ^1.0.8
  responsive_framework: ^1.1.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  very_good_analysis: ^5.1.0


