name: common
description: Common utilities and models
version: 0.0.1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  device_info_plus: ^9.1.1
  firebase_core: ^2.24.0
  firebase_dynamic_links: ^5.4.6
  firebase_messaging: ^14.7.6
  flutter:
    sdk: flutter
  go_router: ^13.0.1
  local_auth: ^2.1.7
  package_info_plus: ^8.1.3
  rxdart: ^0.27.7
  shared_preferences: ^2.2.2
  socket_io_client: ^2.0.3+1
  universal_io: ^2.2.2
  connectivity_plus: ^6.1.2
  values:
    path: ../values

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
  flutter_lints: ^3.0.1


